import os, pathlib

# TODO: there is a timing bug without this
os.environ["AMD_AQL"] = "1"

from tinygrad.device import Device
from tinygrad.runtime.support.compiler_amd import HIPCompiler
from extra.assembly.amd.dsl import Reg, s

NUM_WORKGROUPS = 96
WAVE_SIZE = 32
NUM_WAVES = 2
FLOPS_PER_MATMUL = 16*16*16*2
INTERNAL_LOOP = 1_000_00
INSTRUCTIONS_PER_LOOP = 200
DIRECTIVE = ".amdhsa_wavefront_size32 1"

assemblyTemplate = (pathlib.Path(__file__).parent / "template.s").read_text()
assemblyTemplateOld = (pathlib.Path(__file__).parent / "template_old.s").read_text()

def build_loop(mma_inst, loop_insts) -> bytes:
  """Build loop body bytes: MMA instructions + loop control (sub, cmp, branch)."""
  mma_bytes = b"".join([mma_inst.to_bytes() for _ in range(INSTRUCTIONS_PER_LOOP)])
  # Calculate branch offset: go back to start of MMA instructions
  # simm16 is signed offset in dwords from PC+4 (after branch instruction)
  s_sub, s_cmp, s_branch, s_end = loop_insts
  # Size from start of loop to end of branch instruction (PC after branch)
  loop_size = len(mma_bytes) + s_sub.size() + s_cmp.size() + s_branch.size()
  branch_offset = -(loop_size // 4)  # target is start of mma_bytes
  # Rebuild branch with correct offset
  s_branch = type(s_branch)(s_branch.op, simm16=branch_offset & 0xFFFF)
  return mma_bytes + s_sub.to_bytes() + s_cmp.to_bytes() + s_branch.to_bytes() + s_end.to_bytes()

def launchBenchmark(instruction, vgprIndices, dense=True, accum=False, **kwargs):
  if accum:
    inst = instruction(v[0:vgprIndices[0]], v[vgprIndices[1]:vgprIndices[2]], v[vgprIndices[1]:vgprIndices[2]], 1, acc_cd=1, **kwargs)
  elif dense:
    inst = instruction(v[0:vgprIndices[0]], v[vgprIndices[1]:vgprIndices[2]], v[vgprIndices[1]:vgprIndices[2]], 1)
  else:
    inst = instruction(v[0:vgprIndices[0]], v[vgprIndices[1]:vgprIndices[2]], v[vgprIndices[3]:vgprIndices[4]], v[vgprIndices[5]])
  vgprs:set = set()
  for n,_ in inst._fields:
    if isinstance(val:=getattr(inst, n), Reg) and val.offset >= v.offset: vgprs |= {val.offset+i for i in range(val.sz)}
  vgpr_count = str(max(vgprs)+1)

  # OLD: use template_old.s with assembler mnemonics
  inst_bytes = b"".join([inst.to_bytes() for _ in range(INSTRUCTIONS_PER_LOOP)])
  inst_hex = "\n".join("  .byte " + ",".join(f"0x{b:02x}" for b in inst_bytes[i:i+16]) for i in range(0, len(inst_bytes), 16)) + "\n"
  src_old = assemblyTemplateOld.replace("INTERNAL_LOOP", str(INTERNAL_LOOP)).replace("INSTRUCTION", inst_hex)
  src_old = src_old.replace("VGPR_COUNT", vgpr_count).replace("DIRECTIVE", DIRECTIVE)
  lib_old = COMPILER.compile(src_old)

  # NEW: use template.s with DSL-generated bytes
  loop_bytes = build_loop(inst, LOOP_INSTS)
  loop_hex = "\n".join("  .byte " + ",".join(f"0x{b:02x}" for b in loop_bytes[i:i+16]) for i in range(0, len(loop_bytes), 16)) + "\n"
  preamble = s_mov_b32(s[1], INTERNAL_LOOP).to_bytes() + s_mov_b32(s[2], 0).to_bytes()
  preamble_hex = "  .byte " + ",".join(f"0x{b:02x}" for b in preamble) + "\n"
  src_new = assemblyTemplate.replace("PREAMBLE", preamble_hex).replace("LOOP", loop_hex)
  src_new = src_new.replace("VGPR_COUNT", vgpr_count).replace("DIRECTIVE", DIRECTIVE)
  lib_new = COMPILER.compile(src_new)

  # Verify identical .text section (ELF metadata differs due to labels/mnemonics in old template)
  from tinygrad.runtime.support.elf import elf_loader
  text_old = next(sh.content for sh in elf_loader(lib_old)[1] if sh.name == ".text")
  text_new = next(sh.content for sh in elf_loader(lib_new)[1] if sh.name == ".text")
  assert text_old == text_new, f".text mismatch for {inst.op_name}"

  fxn = DEV.runtime("matmul", lib_new)
  elapsed = min([fxn(global_size=(NUM_WORKGROUPS,1,1), local_size=(WAVE_SIZE*NUM_WAVES,1,1), wait=True) for _ in range(2)])
  FLOPs = FLOPS_PER_MATMUL * NUM_WAVES * NUM_WORKGROUPS * INTERNAL_LOOP * INSTRUCTIONS_PER_LOOP
  print(f"{inst.op_name.lower():<29} : {FLOPs/elapsed/10**12:.2f} T(FL)OPS")

if __name__=="__main__":
  DEV = Device[Device.DEFAULT]
  arch = DEV.renderer.arch

  COMPILER = HIPCompiler(arch)
  if arch in {'gfx1100', 'gfx1103', 'gfx1151'}:
    from extra.assembly.amd.autogen.rdna3.ins import *
    LOOP_INSTS = [s_sub_u32(s[1], s[1], 1), s_cmp_lg_i32(s[1], s[2]), s_cbranch_scc1(simm16=0), s_endpgm()]
    if arch == 'gfx1103': NUM_WORKGROUPS = 8
    if arch == 'gfx1151': NUM_WORKGROUPS = 32
    launchBenchmark(v_wmma_bf16_16x16x16_bf16, (7,8,15))
    launchBenchmark(v_wmma_f16_16x16x16_f16, (7,8,15))
    launchBenchmark(v_wmma_f32_16x16x16_bf16, (7,8,15))
    launchBenchmark(v_wmma_f32_16x16x16_f16, (7,8,15))
    launchBenchmark(v_wmma_i32_16x16x16_iu4, (7,8,9))
    launchBenchmark(v_wmma_i32_16x16x16_iu8, (7,8,11))
  elif arch in {'gfx1200', 'gfx1201'}:
    from extra.assembly.amd.autogen.rdna4.ins import *
    LOOP_INSTS = [s_sub_co_u32(s[1], s[1], 1), s_cmp_lg_i32(s[1], s[2]), s_cbranch_scc1(simm16=0), s_endpgm()]
    NUM_WORKGROUPS = 64
    launchBenchmark(v_wmma_bf16_16x16x16_bf16, (3,4,7))
    launchBenchmark(v_wmma_f16_16x16x16_f16, (3,4,7))
    launchBenchmark(v_wmma_f32_16x16x16_bf16, (7,8,11))
    launchBenchmark(v_wmma_f32_16x16x16_f16, (7,8,11))
    launchBenchmark(v_wmma_i32_16x16x16_iu4, (7,8,8))
    launchBenchmark(v_wmma_i32_16x16x16_iu8, (7,8,9))
    launchBenchmark(v_wmma_f32_16x16x16_fp8_fp8, (7,8,9))
    launchBenchmark(v_wmma_f32_16x16x16_fp8_bf8, (7,8,9))
    launchBenchmark(v_wmma_f32_16x16x16_bf8_fp8, (7,8,9))
    launchBenchmark(v_wmma_f32_16x16x16_bf8_bf8, (7,8,9))
    FLOPS_PER_MATMUL = 16*16*32*2
    launchBenchmark(v_wmma_i32_16x16x32_iu4, (7,8,9))
    launchBenchmark(v_swmmac_f32_16x16x32_f16, (7,8,11,12,19,20), False)
    launchBenchmark(v_swmmac_f32_16x16x32_bf16, (7,8,11,12,19,20), False)
    launchBenchmark(v_swmmac_f16_16x16x32_f16, (3,4,7,8,15,16), False)
    launchBenchmark(v_swmmac_bf16_16x16x32_bf16, (3,4,7,8,15,16), False)
    launchBenchmark(v_swmmac_i32_16x16x32_iu8, (7,8,9,10,13,14), False)
    launchBenchmark(v_swmmac_i32_16x16x32_iu4, (7,8,8,9,10,11), False)
    launchBenchmark(v_swmmac_f32_16x16x32_fp8_fp8, (7,8,9,10,13,14), False)
    launchBenchmark(v_swmmac_f32_16x16x32_fp8_bf8, (7,8,9,10,13,14), False)
    launchBenchmark(v_swmmac_f32_16x16x32_bf8_fp8, (7,8,9,10,13,14), False)
    launchBenchmark(v_swmmac_f32_16x16x32_bf8_bf8, (7,8,9,10,13,14), False)
    FLOPS_PER_MATMUL = 16*16*64*2
    launchBenchmark(v_swmmac_i32_16x16x64_iu4, (7,8,9,10,13,14), False)
  elif arch == 'gfx950':
    from extra.assembly.amd.autogen.cdna.ins import *
    LOOP_INSTS = [s_sub_u32(s[1], s[1], 1), s_cmp_lg_i32(s[1], s[2]), s_cbranch_scc1(simm16=0), s_endpgm()]
    DIRECTIVE = ".amdhsa_accum_offset 4"
    NUM_WORKGROUPS = 256
    WAVE_SIZE = 64
    NUM_WAVES = 4
    launchBenchmark(v_mfma_f32_16x16x16_f16, (3,0,1), accum=True)
    launchBenchmark(v_mfma_f32_16x16x16_bf16, (3,0,1), accum=True)
    FLOPS_PER_MATMUL = 16*16*32*2
    launchBenchmark(v_mfma_f32_16x16x32_f16, (3,0,3), accum=True)
    launchBenchmark(v_mfma_f32_16x16x32_bf16, (3,0,3), accum=True)
    FLOPS_PER_MATMUL = 16*16*128*2
    launchBenchmark(v_mfma_f32_16x16x128_f8f6f4, (3,0,7), accum=True) # fp8
    launchBenchmark(v_mfma_f32_16x16x128_f8f6f4, (3,0,5), accum=True, cbsz=2, blgp=2) # fp6
    launchBenchmark(v_mfma_f32_16x16x128_f8f6f4, (3,0,3), accum=True, cbsz=4, blgp=4) # fp4
  else:
    raise RuntimeError(f"arch {arch} not supported.")
