name: Check Line Counts
on:
  pull_request_target:

# Cancel the workflow in progress in newer build is about to start.
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  checkbranch:
    name: Check PR Branch status
    runs-on: ubuntu-latest
    outputs:
      branchstat: ${{ steps.brstat.outputs.stat}}
    steps:
      - name: Check code from PR branch 
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - name: Check no new noqa E501
        run: |
          has_noqa=false
          git diff upstream/master...new-dd -- . ':(exclude)test/*' --unified=0 | grep -E '^\+|^\-' | while read -r line; do
            if [[ $line == \-* ]]; then
                if [[ "$line" == *"# noqa: E501"* ]]; then
                  has_noqa=true
                fi
            else
              if [[ "$line" == *"# noqa: E501"* ]] && ! $has_noqa; then
                 echo "found a new # noqa: E501"
                 exit 1
              fi
             has_noqa=false
           fi
          done
